### ISSUE TITLE
Toaq Delta Release

### ISSUE THREAD

**Issue by wyattjohnsonbro** [uakci/toadua#18]
Now, many of the definitions are of Toaq Gamma, and so I believe this warrants a nuking of the dictionary (or, at the very least, a search+replace)

**Comment by salarua** [comment]
Unnecessary in my opinion. Most of the words and definitions are still well-formed, and those that aren't can be easily updated.

**Comment by uakci** [comment]
I concur with @salarua – besides, I don’t think any of us would be down to comb through 19,000 entries.
